# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-25 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('gender', models.CharField(max_length=15)),
                ('cellphone', models.CharField(max_length=11)),
                ('cedula', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(max_length=90, unique=True)),
                ('birthday', models.DateField()),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
